### ISSUE TITLE
How to run on MCU

### ISSUE THREAD

**Issue by huigang39** [dxing-cs/TinyLight#2]
It only outputs some repeated values, how can control the real LED light.
![image](https://user-images.githubusercontent.com/63324254/216820961-595e9015-2ffd-4203-9c09-24516bdad1fb.png)

**Comment by dxing-cs** [comment]
Thanks for your question! The provided code is used to evaluate the running time of our derived model on MCU. It does not include IO operations (since it is task-specific and irrelevant to our work's goal). 

To achieve your target, I believe you can map the action to the actual light phase and then control the LED accordingly. Here is an example showing [how to control LED](https://docs.arduino.cc/built-in-examples/basics/Blink).

**Comment by huigang39** [comment]
> Thanks for your question! The provided code is used to evaluate (评价) the running time of our derived (派生) model on MCU. It does not include IO operations (since it is task-specific and irrelevant to our work's goal).
> 
> To achieve your target, I believe you can map the action to the actual light phase (相) and then control the LED accordingly (据此) . Here is an example showing [how to control LED](https://docs.arduino.cc/built-in-examples/basics/Blink).

Thanks for your reply, can I control the duration of the traffic light just by including model.h?

**Comment by huigang39** [comment]
> Thanks for your question! The provided code is used to evaluate (评价) the running time of our derived (派生) model on MCU. It does not include IO operations (since it is task-specific and irrelevant to our work's goal).
> 
> To achieve your target, I believe you can map the action to the actual light phase (相) and then control the LED accordingly (据此) . Here is an example showing [how to control LED](https://docs.arduino.cc/built-in-examples/basics/Blink).

Thanks for your reply, can I control the duration of the traffic light just by including model.h?

**Comment by dxing-cs** [comment]
Sorry, the model.h file only contains parameters used for the decision-making. It does not include duration control on the MCU. 

> > Thanks for your question! The provided code is used to evaluate (评价) the running time of our derived (派生) model on MCU. It does not include IO operations (since it is task-specific and irrelevant to our work's goal).
> > To achieve your target, I believe you can map the action to the actual light phase (相) and then control the LED accordingly (据此) . Here is an example showing [how to control LED](https://docs.arduino.cc/built-in-examples/basics/Blink).
> 
> Thanks for your reply, can I control the duration of the traffic light just by including model.h?

**Comment by huigang39** [comment]
> Sorry, the model.h file only contains parameters used for the decision-making. It does not include duration (工期) control on the MCU.
> 
> > > Thanks for your question! The provided code is used to 
> > >         
> > >           evaluate
> > >           (评价)
> > >         
> > >          (评价) the running time of our 
> > >         
> > >           derived
> > >           (派生)
> > >         
> > >          (派生) model on MCU. It does not include IO operations (since it is task-specific and irrelevant to our work's goal).
> > > To achieve your target, I believe you can map the action to the actual light 
> > >         
> > >           phase
> > >           (相)
> > >         
> > >          (相) and then control the LED 
> > >         
> > >           accordingly
> > >           (据此)
> > >         
> > >          (据此) . Here is an example showing [how to control LED](https://docs.arduino.cc/built-in-examples/basics/Blink).
> > 
> > 
> > Thanks for your reply, can I control the 
> >         
> >           duration
> >           (工期)
> >         
> >          of the traffic light just by including model.h?

OK，thank you.
